import { createContext, useContext, useState } from 'react'

const t = {
  fr: {
    home:'Accueil', dashboard:'Mon espace', login:'Connexion', register:"S'inscrire", logout:'Déconnexion',
    badge:'Assistant IA pour étudiants marocains',
    heroTitle:'Ton assistant', heroTitleBold:'intelligent',
    heroDesc:'Résumés, quiz, flashcards, examens blancs — tout en un.',
    startBtn:'Commencer maintenant',
    feat1Title:'Chat IA', feat1Desc:'Pose tes questions, obtiens des réponses pédagogiques.',
    feat2Title:'Résumé + PDF', feat2Desc:'Importe un PDF ou une image, reçois un résumé.',
    feat3Title:'Quiz QCM', feat3Desc:'Génère des questions depuis ton cours.',
    feat4Title:'Orientation', feat4Desc:'Trouve ta filière idéale.',
    feat5Title:'Flashcards', feat5Desc:'Mémorise avec des fiches interactives.',
    feat6Title:'Mode Examen', feat6Desc:'Entraîne-toi avec un timer et un rapport.',
    welcomeBack:'Bon retour,', chooseFeature:"Que veux-tu faire aujourd'hui ?",
    chatTitle:'Assistant IA', chatDesc:'Pose toutes tes questions.',
    summaryTitle:'Résumé + PDF', summaryDesc:'Résume un cours ou importe un fichier.',
    quizTitle:'Quiz QCM', quizDesc:'Génère des questions depuis ton cours.',
    orientTitle:'Orientation', orientDesc:'Trouve ta filière idéale.',
    flashTitle:'Flashcards', flashDesc:'Mémorise avec des fiches Q&R.',
    examTitle:'Mode Examen', examDesc:'Examen blanc avec timer et score.',
    loginTitle:'Connexion', loginSub:'Bienvenue ! Connecte-toi.',
    emailLabel:'Email', passLabel:'Mot de passe', nameLabel:'Nom complet',
    loginBtn:'Se connecter', registerBtn:"S'inscrire",
    noAccount:'Pas de compte ?', hasAccount:'Déjà un compte ?',
    registerTitle:'Créer un compte', registerSub:"Rejoins l'aventure !",
    chatWelcome:'Salam ! Je suis ton assistant IA 🎓\nPose-moi tes questions sur tes cours ou ton orientation.',
    chatPlaceholder:'Pose ta question...',
    quickQ1:'Comment réviser efficacement ?',
    quickQ2:'Explique les équations du 2nd degré',
    quickQ3:'Quelles filières après le Bac S ?',
    quickQ4:'Aide-moi à faire un plan de révision',
    summaryPageTitle:'Résumé de cours', summaryPageSub:'Texte, PDF ou image → résumé structuré',
    summaryPlaceholder:'Colle ton cours ici...', summaryBtn:'Générer le résumé',
    uploadClick:'Clique', uploadDrag:'ou glisse un PDF / une image ici',
    quizPageTitle:'Quiz de révision', quizPageSub:'Génère des QCM depuis ton cours',
    quizCoursePlaceholder:'Colle ton cours (optionnel)...',
    quizSubjectPlaceholder:'Ou entre une matière (ex: Maths, Histoire...)',
    quizBtn:'Générer le quiz', quizNext:'Suivant', quizFinish:'Voir mon score',
    quizRestart:'Recommencer', quizScore:'Ton score',
    orientPageTitle:'Orientation scolaire', orientPageSub:'Décris ton profil',
    orientPlaceholder:'Ex: 16/20 en maths, j\'aime l\'informatique...', orientBtn:'Obtenir des recommandations',
    flashSub:'Génère des fiches question/réponse depuis ton cours',
    flashPlaceholder:'Colle ton cours ici...', flashBtn:'Générer les flashcards',
    flashClickHint:'Clique pour révéler la réponse',
    prev:'Précédent', next:'Suivant', flip:'Retourner', newDeck:'Nouveau deck',
    examSub:'Entraîne-toi avec un vrai examen chronométré',
    examSubject:'Matière', examNumQ:'Nombre de questions', examDuration:'Durée',
    startExam:'Démarrer l\'examen', submitExam:'Terminer',
    examAnswered:'répondues', newExam:'Nouvel examen',
    examExcellent:'Excellent ! 🏆', examGood:'Bien joué ! 👍', examKeepGoing:'Continue tes efforts ! 📚',
    statTotal:'Sessions totales', statChats:'Chats', statSummaries:'Résumés', statQuizzes:'Quiz',
    recentActivity:'Activité récente', progressTitle:'Ma progression',
    profileTitle:'Mon profil',
  },
  ar: {
    home:'الرئيسية', dashboard:'فضائي', login:'تسجيل الدخول', register:'إنشاء حساب', logout:'خروج',
    badge:'مساعد ذكي للطلاب المغاربة',
    heroTitle:'مساعدك', heroTitleBold:'الذكي',
    heroDesc:'ملخصات، اختبارات، بطاقات تعليمية، امتحانات تجريبية — كل شيء في مكان واحد.',
    startBtn:'ابدأ الآن',
    feat1Title:'المحادثة الذكية', feat1Desc:'اطرح أسئلتك واحصل على إجابات تعليمية.',
    feat2Title:'ملخص + PDF', feat2Desc:'استورد PDF أو صورة واحصل على ملخص.',
    feat3Title:'اختبار QCM', feat3Desc:'أنشئ أسئلة من درسك.',
    feat4Title:'التوجيه المدرسي', feat4Desc:'اعثر على مسارك المثالي.',
    feat5Title:'البطاقات التعليمية', feat5Desc:'احفظ بالبطاقات التفاعلية.',
    feat6Title:'وضع الامتحان', feat6Desc:'تدرب مع مؤقت وتقرير نهائي.',
    welcomeBack:'مرحباً بعودتك،', chooseFeature:'ماذا تريد أن تفعل اليوم؟',
    chatTitle:'المساعد الذكي', chatDesc:'اطرح جميع أسئلتك.',
    summaryTitle:'ملخص + PDF', summaryDesc:'لخص درسًا أو استورد ملفًا.',
    quizTitle:'اختبار QCM', quizDesc:'أنشئ أسئلة من درسك.',
    orientTitle:'التوجيه', orientDesc:'اعثر على مسارك المثالي.',
    flashTitle:'البطاقات التعليمية', flashDesc:'احفظ ببطاقات سؤال/جواب.',
    examTitle:'وضع الامتحان', examDesc:'امتحان تجريبي مع مؤقت ونتيجة.',
    loginTitle:'تسجيل الدخول', loginSub:'مرحباً! سجل دخولك.',
    emailLabel:'البريد الإلكتروني', passLabel:'كلمة المرور', nameLabel:'الاسم الكامل',
    loginBtn:'دخول', registerBtn:'إنشاء حساب',
    noAccount:'ليس لديك حساب؟', hasAccount:'لديك حساب؟',
    registerTitle:'إنشاء حساب', registerSub:'انضم إلى المجتمع!',
    chatWelcome:'السلام عليكم! أنا مساعدك الذكي 🎓\nاطرح أسئلتك حول دروسك أو توجيهك.',
    chatPlaceholder:'اطرح سؤالك...',
    quickQ1:'كيف أراجع بفعالية؟',
    quickQ2:'اشرح معادلات الدرجة الثانية',
    quickQ3:'ما هي المسارات بعد الباكالوريا؟',
    quickQ4:'ساعدني في وضع خطة مراجعة',
    summaryPageTitle:'ملخص الدرس', summaryPageSub:'نص أو PDF أو صورة ← ملخص منظم',
    summaryPlaceholder:'الصق درسك هنا...', summaryBtn:'إنشاء الملخص',
    uploadClick:'انقر', uploadDrag:'أو اسحب PDF أو صورة هنا',
    quizPageTitle:'اختبار المراجعة', quizPageSub:'أنشئ أسئلة QCM',
    quizCoursePlaceholder:'الصق درسك (اختياري)...',
    quizSubjectPlaceholder:'أو أدخل مادة (مثال: رياضيات، تاريخ...)',
    quizBtn:'إنشاء الاختبار', quizNext:'التالي', quizFinish:'عرض نتيجتي',
    quizRestart:'البدء من جديد', quizScore:'نتيجتك',
    orientPageTitle:'التوجيه المدرسي', orientPageSub:'صف ملفك الشخصي',
    orientPlaceholder:'مثال: 16 في الرياضيات، أحب الإعلاميات...', orientBtn:'الحصول على توصيات',
    flashSub:'أنشئ بطاقات سؤال/جواب من درسك',
    flashPlaceholder:'الصق درسك هنا...', flashBtn:'إنشاء البطاقات',
    flashClickHint:'انقر للكشف عن الإجابة',
    prev:'السابق', next:'التالي', flip:'قلب', newDeck:'مجموعة جديدة',
    examSub:'تدرب بامتحان حقيقي مع توقيت',
    examSubject:'المادة', examNumQ:'عدد الأسئلة', examDuration:'المدة',
    startExam:'بدء الامتحان', submitExam:'إنهاء',
    examAnswered:'تمت الإجابة', newExam:'امتحان جديد',
    examExcellent:'ممتاز! 🏆', examGood:'أحسنت! 👍', examKeepGoing:'واصل الجهد! 📚',
    statTotal:'الجلسات الكلية', statChats:'محادثات', statSummaries:'ملخصات', statQuizzes:'اختبارات',
    recentActivity:'النشاط الأخير', progressTitle:'تقدمي',
    profileTitle:'ملفي الشخصي',
  }
}

const LangContext = createContext()

export function LangProvider({ children }) {
  const [lang, setLang] = useState('fr')
  const isRTL = lang === 'ar'

  return (
    <LangContext.Provider value={{ lang, setLang, t: t[lang], isRTL }}>
      <div dir={isRTL ? 'rtl' : 'ltr'} className={isRTL ? 'rtl' : ''}>
        {children}
      </div>
    </LangContext.Provider>
  )
}

export const useLang = () => useContext(LangContext)
